# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# 每日早9点到晚8点每2小时运行一次

name: 中青自动阅读3

on:
  workflow_dispatch:
  schedule:
     - cron: '6 1-22/5 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ9 }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ10 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ11 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ12 }}
      TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读9】'
        if: env.YOUTH_READ
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ9 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME }}

      - name: '运行 【中青看点自动阅读10】'
        if: env.YOUTH_READ2
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ10 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME2 }}
          
      - name: '运行 【中青看点自动阅读11】'
        if: env.YOUTH_READ3
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ11 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME3 }}
          
      - name: '运行 【中青看点自动阅读12】'
        if: env.YOUTH_READ4
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ12 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME4 }}
